// This file is part of the happyDomain (R) project.
// Copyright (c) 2020-2025 happyDomain
// Authors: Pierre-Olivier Mercier, et al.
//
// This program is offered under a commercial and under the AGPL license.
// For commercial licensing, contact us at <contact@happydomain.org>.
//
// For AGPL licensing:
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

package happydns

import (
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"path"
	"strings"
)

// Options stores the configuration of the software.
type Options struct {
	// AdminBind is the address:port or unix socket used to serve the admin
	// API.
	AdminBind string

	// AdminPasswordHash gates access to the admin interface. When empty, the
	// admin API is served without application-layer authentication (safe only
	// behind the default local unix socket). When set, it holds either a bcrypt
	// hash (recommended, generated by `happydomain admin-hash`) or a cleartext
	// password (accepted with a startup warning). Operators log in with the
	// matching password to obtain a short-lived admin session token.
	AdminPasswordHash string

	// Bind is the address:port used to bind the main interface with API.
	Bind string

	// BasePath is the relative path where begins the root of the app.
	BasePath string

	// DevProxy is the URL that override static assets.
	DevProxy string

	// DefaultNameServer is the NS server suggested by default.
	DefaultNameServer string

	// DisableProviders should disallow all actions on provider (add/edit/delete) through public API.
	DisableProviders bool

	// DisableRegistration forbids all new registration using the public form/API.
	DisableRegistration bool

	// DisableEmbeddedLogin disables the internal user/password login in favor of ExternalAuth or OIDC.
	DisableEmbeddedLogin bool

	// ExternalAuth is the URL of the login form to use instead of the embedded one.
	ExternalAuth url.URL

	// ExternalURL keeps the URL used in communications (such as email,
	// ...), when it needs to use complete URL, not only relative parts.
	ExternalURL url.URL

	// JWTSecretKey stores the private key to sign and verify JWT tokens.
	JWTSecretKey []byte

	// JWTSigningMethod is the signing method to check token signature.
	JWTSigningMethod string

	// NoAuth controls if there is user access control or not.
	NoAuth bool

	// OptOutInsights disable the anonymous usage statistics report.
	OptOutInsights bool

	// StorageEngine points to the storage engine used.
	StorageEngine string

	ListmonkURL url.URL
	ListmonkID  int

	// MailFrom holds the content of the From field for all e-mails that
	// will be send.
	MailFrom mail.Address

	NoMail               bool
	MailSMTPHost         string
	MailSMTPPort         uint
	MailSMTPUsername     string
	MailSMTPPassword     string
	MailSMTPTLSSNoVerify bool

	OIDCClients []OIDCSettings

	// CaptchaProvider selects the captcha provider ("hcaptcha", "recaptchav2", "turnstile", or "").
	CaptchaProvider string

	// CaptchaLoginThreshold is the number of consecutive login failures before captcha is required.
	// 0 means always require captcha at login (when provider is configured).
	CaptchaLoginThreshold int
}

// HasNetworkAdminBind reports whether AdminBind designates a network address
// rather than a unix socket path. It gates the requirement for an admin
// password, so it deliberately errs on the side of treating an ambiguous value
// as network-exposed.
func (o *Options) HasNetworkAdminBind() bool {
	return strings.Contains(o.AdminBind, ":")
}

// HasLoopbackAdminBind reports whether AdminBind is a network address whose
// host part is restricted to the loopback interface. Such a bind is only
// reachable from the machine itself (or from whatever reverse proxy runs on
// it), so it is not treated as network-exposed when checking for an admin
// password. An address without an explicit host (":8082") listens on every
// interface and is therefore not loopback.
func (o *Options) HasLoopbackAdminBind() bool {
	if !o.HasNetworkAdminBind() {
		return false
	}

	host, _, err := net.SplitHostPort(o.AdminBind)
	if err != nil {
		return false
	}

	if host == "localhost" {
		return true
	}

	ip := net.ParseIP(host)
	return ip != nil && ip.IsLoopback()
}

// GetBaseURL returns the full url to the absolute ExternalURL, including BaseURL.
func (o *Options) GetBaseURL() string {
	return fmt.Sprintf("%s%s", o.ExternalURL.String(), o.BasePath)
}

func (o *Options) GetAuthURL() *url.URL {
	redirecturl := o.ExternalURL
	redirecturl.Path = path.Join(redirecturl.Path, o.BasePath, "auth", "callback")
	return &redirecturl
}
