FROM alpine

EXPOSE 8081

ENTRYPOINT ["/usr/sbin/happydns"]

ENV HAPPYDNS_LEVELDB_PATH=/data/happydns.db

VOLUME /data

RUN adduser --system --no-create-home --uid 15353 happydns && chown happydns /data
USER happydns

COPY happydns /usr/sbin/happydns
COPY hadmin.sh /usr/bin/hadmin
