FROM alpine:3.18

EXPOSE 8081

ENTRYPOINT ["/usr/sbin/happyDomain"]

ENV HAPPYDOMAIN_LEVELDB_PATH=/data/happydomain.db

RUN apk add --no-cache \
        curl \
        jq \
    && \
    adduser --system --no-create-home --uid 15353 happydomain && \
    mkdir /data && chown happydomain /data
USER happydomain
WORKDIR /data

VOLUME /data

COPY happydomain /usr/sbin/happyDomain
COPY hadmin.sh /usr/bin/hadmin
