// This file is generated by go generate

import type { ServiceInfos } from "$lib/model/service_specs.svelte";
export const servicesSpecs: Record<string, ServiceInfos> = {
    "abstract.ACMEChallenge": {
        "name": "ACME Challenge",
        "_svctype": "abstract.ACMEChallenge",
        "family": "abstract",
        "categories": [
            "temporary",
            "verification"
        ],
        "record_types": null,
        "restrictions": {
            "nearAlone": true
        }
    },
    "abstract.CalDAV": {
        "name": "CalDAV (Calendar)",
        "_svctype": "abstract.CalDAV",
        "family": "abstract",
        "categories": [
            "service",
            "groupware"
        ],
        "record_types": null,
        "restrictions": {
            "nearAlone": true,
            "needTypes": [
                33,
                16
            ],
            "single": true
        }
    },
    "abstract.CardDAV": {
        "name": "CardDAV (Address Book)",
        "_svctype": "abstract.CardDAV",
        "family": "abstract",
        "categories": [
            "service",
            "groupware"
        ],
        "record_types": null,
        "restrictions": {
            "nearAlone": true,
            "needTypes": [
                33,
                16
            ],
            "single": true
        }
    },
    "abstract.Delegation": {
        "name": "Delegation",
        "_svctype": "abstract.Delegation",
        "family": "abstract",
        "categories": [
            "domain name"
        ],
        "record_types": [
            2,
            43
        ],
        "restrictions": {
            "alone": true,
            "exclusive": [
                "abstract.Origin",
                "abstract.NSOnlyOrigin"
            ],
            "leaf": true,
            "needTypes": [
                2
            ],
            "single": true
        }
    },
    "abstract.EmailAutoConfig": {
        "name": "Email Auto-configuration",
        "_svctype": "abstract.EmailAutoConfig",
        "family": "abstract",
        "categories": [
            "email"
        ],
        "record_types": [
            33,
            5
        ],
        "restrictions": {
            "nearAlone": true,
            "needTypes": [
                33
            ],
            "single": true
        }
    },
    "abstract.GithubOrgVerif": {
        "name": "GitHub Verification",
        "_svctype": "abstract.GithubOrgVerif",
        "family": "abstract",
        "categories": [
            "verification"
        ],
        "record_types": null,
        "restrictions": {
            "nearAlone": true
        }
    },
    "abstract.GitlabPageVerif": {
        "name": "Gitlab Pages Verification",
        "_svctype": "abstract.GitlabPageVerif",
        "family": "abstract",
        "categories": [
            "verification"
        ],
        "record_types": null,
        "restrictions": {
            "nearAlone": true
        }
    },
    "abstract.GoogleVerif": {
        "name": "Google Verification",
        "_svctype": "abstract.GoogleVerif",
        "family": "abstract",
        "categories": [
            "verification"
        ],
        "record_types": null,
        "restrictions": {}
    },
    "abstract.Kerberos": {
        "name": "Kerberos",
        "_svctype": "abstract.Kerberos",
        "family": "abstract",
        "categories": [
            "service",
            "authentication"
        ],
        "record_types": null,
        "restrictions": {
            "nearAlone": true,
            "needTypes": [
                33
            ],
            "single": true
        }
    },
    "abstract.KeybaseVerif": {
        "name": "Keybase Verification",
        "_svctype": "abstract.KeybaseVerif",
        "family": "abstract",
        "categories": [
            "verification"
        ],
        "record_types": null,
        "restrictions": {
            "nearAlone": true
        }
    },
    "abstract.LDAP": {
        "name": "LDAP Directory",
        "_svctype": "abstract.LDAP",
        "family": "abstract",
        "categories": [
            "service"
        ],
        "record_types": null,
        "restrictions": {
            "nearAlone": true,
            "needTypes": [
                33
            ],
            "single": true
        }
    },
    "abstract.LibravatarServer": {
        "name": "Federated Avatar",
        "_svctype": "abstract.LibravatarServer",
        "family": "abstract",
        "categories": [
            "service"
        ],
        "record_types": null,
        "restrictions": {}
    },
    "abstract.MatrixIM": {
        "name": "Matrix IM",
        "_svctype": "abstract.MatrixIM",
        "family": "abstract",
        "categories": [
            "service"
        ],
        "record_types": null,
        "restrictions": {
            "nearAlone": true,
            "needTypes": [
                33
            ],
            "single": true
        }
    },
    "abstract.NSOnlyOrigin": {
        "name": "Origin",
        "_svctype": "abstract.NSOnlyOrigin",
        "family": "hidden",
        "categories": [
            "domain name"
        ],
        "record_types": [
            2
        ],
        "restrictions": {
            "needTypes": [
                2
            ],
            "rootOnly": true,
            "single": true
        }
    },
    "abstract.OpenPGP": {
        "name": "PGP Key",
        "_svctype": "abstract.OpenPGP",
        "family": "abstract",
        "categories": [
            "email"
        ],
        "record_types": [
            61
        ],
        "restrictions": {
            "nearAlone": true,
            "needTypes": [
                61
            ]
        }
    },
    "abstract.Origin": {
        "name": "Origin",
        "_svctype": "abstract.Origin",
        "family": "abstract",
        "categories": [
            "domain name"
        ],
        "record_types": [
            6,
            2
        ],
        "restrictions": {
            "needTypes": [
                6
            ],
            "rootOnly": true,
            "single": true
        }
    },
    "abstract.RFC6186": {
        "name": "E-Mail Services Discovery",
        "_svctype": "abstract.RFC6186",
        "family": "abstract",
        "categories": [
            "email"
        ],
        "record_types": null,
        "restrictions": {
            "nearAlone": true,
            "needTypes": [
                33
            ],
            "single": true
        }
    },
    "abstract.SIP": {
        "name": "SIP / VoIP",
        "_svctype": "abstract.SIP",
        "family": "abstract",
        "categories": [
            "service",
            "voip"
        ],
        "record_types": null,
        "restrictions": {
            "nearAlone": true,
            "needTypes": [
                33
            ],
            "single": true
        }
    },
    "abstract.SMimeCert": {
        "name": "SMimeCert",
        "_svctype": "abstract.SMimeCert",
        "family": "abstract",
        "categories": [
            "email"
        ],
        "record_types": [
            53
        ],
        "restrictions": {
            "nearAlone": true,
            "needTypes": [
                53
            ]
        }
    },
    "abstract.ScalewayChallenge": {
        "name": "Scaleway Challenge",
        "_svctype": "abstract.ScalewayChallenge",
        "family": "abstract",
        "categories": [
            "verification"
        ],
        "record_types": null,
        "restrictions": {
            "nearAlone": true
        }
    },
    "abstract.Server": {
        "name": "Server",
        "_svctype": "abstract.Server",
        "family": "abstract",
        "categories": [
            "server"
        ],
        "record_types": [
            1,
            28,
            44
        ],
        "restrictions": {
            "glue": true
        }
    },
    "abstract.XMPP": {
        "name": "XMPP IM",
        "_svctype": "abstract.XMPP",
        "family": "abstract",
        "categories": [
            "service"
        ],
        "record_types": null,
        "restrictions": {
            "nearAlone": true,
            "needTypes": [
                33
            ],
            "single": true
        }
    },
    "google.GSuite": {
        "name": "G Suite",
        "_svctype": "google.GSuite",
        "_svcicon": "/api/service_specs/google.GSuite/icon.png",
        "family": "provider",
        "categories": [
            "email"
        ],
        "record_types": null,
        "restrictions": {
            "exclusive": [
                "abstract.EMail",
                "svcs.MX"
            ],
            "needTypes": [
                15
            ],
            "single": true
        }
    },
    "svcs.Alias": {
        "name": "Alias",
        "_svctype": "svcs.Alias",
        "family": "",
        "categories": [
            "alias"
        ],
        "record_types": [
            5,
            39,
            65280,
            65281,
            65284,
            65282,
            65283,
            65285
        ],
        "restrictions": {
            "single": true
        }
    },
    "svcs.BIMI": {
        "name": "BIMI",
        "_svctype": "svcs.BIMI",
        "family": "",
        "categories": [
            "email"
        ],
        "record_types": [
            16
        ],
        "restrictions": {
            "nearAlone": true,
            "needTypes": [
                16
            ]
        }
    },
    "svcs.CAAPolicy": {
        "name": "Certification Authority Authorization",
        "_svctype": "svcs.CAAPolicy",
        "family": "",
        "categories": [
            "security"
        ],
        "record_types": [
            257
        ],
        "restrictions": {
            "needTypes": [
                257
            ],
            "single": true
        }
    },
    "svcs.DKIMRecord": {
        "name": "DKIM",
        "_svctype": "svcs.DKIMRecord",
        "family": "",
        "categories": [
            "email"
        ],
        "record_types": [
            16
        ],
        "restrictions": {
            "nearAlone": true,
            "needTypes": [
                16
            ]
        }
    },
    "svcs.DKIMRedirection": {
        "name": "DKIM external",
        "_svctype": "svcs.DKIMRedirection",
        "family": "",
        "categories": [
            "email"
        ],
        "record_types": [
            5
        ],
        "restrictions": {
            "nearAlone": true,
            "needTypes": [
                5
            ]
        }
    },
    "svcs.DMARC": {
        "name": "DMARC",
        "_svctype": "svcs.DMARC",
        "family": "",
        "categories": [
            "email"
        ],
        "record_types": [
            16
        ],
        "restrictions": {
            "nearAlone": true,
            "needTypes": [
                16
            ]
        }
    },
    "svcs.DMARCReport": {
        "name": "DMARC allow receiving reports",
        "_svctype": "svcs.DMARCReport",
        "family": "",
        "categories": [
            "email"
        ],
        "record_types": [
            16
        ],
        "restrictions": {
            "nearAlone": true,
            "needTypes": [
                16
            ]
        }
    },
    "svcs.ForSale": {
        "name": "Domain For Sale",
        "_svctype": "svcs.ForSale",
        "family": "",
        "categories": [
            "service"
        ],
        "record_types": [
            16
        ],
        "restrictions": {
            "nearAlone": true,
            "needTypes": [
                16
            ],
            "single": true
        }
    },
    "svcs.MTA_STS": {
        "name": "MTA-STS",
        "_svctype": "svcs.MTA_STS",
        "family": "",
        "categories": [
            "email"
        ],
        "record_types": [
            16
        ],
        "restrictions": {
            "nearAlone": true,
            "needTypes": [
                16
            ]
        }
    },
    "svcs.MXs": {
        "name": "E-Mail servers",
        "_svctype": "svcs.MXs",
        "family": "",
        "categories": [
            "email"
        ],
        "record_types": [
            15
        ],
        "restrictions": {
            "needTypes": [
                15
            ],
            "single": true
        }
    },
    "svcs.NAPTR": {
        "name": "Naming Authority Pointer",
        "_svctype": "svcs.NAPTR",
        "family": "",
        "categories": [
            "telephony"
        ],
        "record_types": [
            35
        ],
        "restrictions": {
            "needTypes": [
                35
            ]
        }
    },
    "svcs.Orphan": {
        "name": "Orphan Record",
        "_svctype": "svcs.Orphan",
        "family": "",
        "categories": [],
        "record_types": null,
        "restrictions": {}
    },
    "svcs.PTR": {
        "name": "Pointer",
        "_svctype": "svcs.PTR",
        "family": "",
        "categories": [
            "domain name"
        ],
        "record_types": [
            12
        ],
        "restrictions": {
            "alone": true,
            "needTypes": [
                12
            ],
            "single": true
        }
    },
    "svcs.SPF": {
        "name": "SPF",
        "_svctype": "svcs.SPF",
        "family": "",
        "categories": [
            "email"
        ],
        "record_types": [
            16,
            99
        ],
        "restrictions": {
            "needTypes": [
                16
            ]
        }
    },
    "svcs.SSHFPs": {
        "name": "SSHFP",
        "_svctype": "svcs.SSHFPs",
        "family": "",
        "categories": [
            "security"
        ],
        "record_types": [
            44
        ],
        "restrictions": {
            "needTypes": [
                44
            ]
        }
    },
    "svcs.SpecialCNAME": {
        "name": "SubAlias",
        "_svctype": "svcs.SpecialCNAME",
        "family": "",
        "categories": [
            "alias"
        ],
        "record_types": null,
        "restrictions": {
            "nearAlone": true,
            "needTypes": [
                5
            ]
        }
    },
    "svcs.TLSAs": {
        "name": "TLSA records",
        "_svctype": "svcs.TLSAs",
        "family": "",
        "categories": [
            "security"
        ],
        "record_types": [
            52
        ],
        "restrictions": {
            "nearAlone": true,
            "needTypes": [
                52
            ],
            "single": true
        }
    },
    "svcs.TLS_RPT": {
        "name": "TLS-RPT",
        "_svctype": "svcs.TLS_RPT",
        "family": "",
        "categories": [
            "email"
        ],
        "record_types": [
            16
        ],
        "restrictions": {
            "nearAlone": true,
            "needTypes": [
                16
            ]
        }
    },
    "svcs.TXT": {
        "name": "Text Record",
        "_svctype": "svcs.TXT",
        "family": "",
        "categories": null,
        "record_types": [
            16
        ],
        "restrictions": {
            "needTypes": [
                16
            ]
        }
    },
    "svcs.UnknownSRV": {
        "name": "Service Record",
        "_svctype": "svcs.UnknownSRV",
        "family": "",
        "categories": [
            "service"
        ],
        "record_types": [
            33
        ],
        "restrictions": {
            "nearAlone": true,
            "needTypes": [
                33
            ]
        }
    }
}
