// This file is generated by go generate

import type { dnsRR, dnsTypeA, dnsTypeAAAA, dnsTypeCAA, dnsTypeCNAME, dnsTypeDS, dnsTypeMX, dnsTypeNAPTR, dnsTypeNS, dnsTypeOPENPGPKEY, dnsTypePTR, dnsTypeSMIMEA, dnsTypeSOA, dnsTypeSRV, dnsTypeSSHFP, dnsTypeTLSA, dnsTypeTXT } from "$lib/dns_rr";

// The body each service carries, as the API serializes it.
export interface AbstractACMEChallengeBody {
    txt: dnsTypeTXT;
}

export interface AbstractCalDAVBody {
    records: Array<dnsTypeSRV>;
    paths?: Array<dnsTypeTXT>;
}

export interface AbstractCardDAVBody {
    records: Array<dnsTypeSRV>;
    paths?: Array<dnsTypeTXT>;
}

export interface AbstractDelegationBody {
    ns: Array<dnsTypeNS>;
    ds: Array<dnsTypeDS>;
}

export interface AbstractEmailAutoConfigBody {
    displayName?: string;
    displayShortName?: string;
    incomingAuth?: string;
    outgoingAuth?: string;
    usernameFormat?: string;
    exchangeServer?: string;
    incomingSRV?: dnsTypeSRV;
    outgoingSRV?: dnsTypeSRV;
    autoconfigCNAME?: dnsTypeCNAME;
    autodiscoverCNAME?: dnsTypeCNAME;
    autodiscoverSRV?: dnsTypeSRV;
}

export interface AbstractGithubOrgVerifBody {
    txt: dnsTypeTXT;
}

export interface AbstractGitlabPageVerifBody {
    txt: dnsTypeTXT;
}

export interface AbstractGoogleVerifBody {
    txt: dnsTypeTXT;
}

export interface AbstractKerberosBody {
    kdc_tcp?: Array<dnsTypeSRV>;
    kdc_udp?: Array<dnsTypeSRV>;
    master?: Array<dnsTypeSRV>;
    admin?: Array<dnsTypeSRV>;
    kpasswd_tcp?: Array<dnsTypeSRV>;
    kpasswd_udp?: Array<dnsTypeSRV>;
}

export interface AbstractKeybaseVerifBody {
    txt: dnsTypeTXT;
}

export interface AbstractLDAPBody {
    records: Array<dnsTypeSRV>;
}

export interface AbstractLibravatarServerBody {
    srv: Array<dnsTypeSRV>;
}

export interface AbstractMTASTSBody {
    mode?: string;
    maxAge?: number;
    mx?: Array<string>;
    txt?: dnsTypeTXT;
    policyCNAME?: dnsTypeCNAME;
}

export interface AbstractMatrixIMBody {
    records: Array<dnsTypeSRV>;
}

export interface AbstractNSOnlyOriginBody {
    ns: Array<dnsTypeNS>;
}

export interface AbstractOpenPGPBody {
    username?: string;
    openpgpkey: dnsTypeOPENPGPKEY;
}

export interface AbstractOriginBody {
    soa: dnsTypeSOA;
    ns: Array<dnsTypeNS>;
}

export interface AbstractRFC6186Body {
    srv: Array<dnsTypeSRV>;
}

export interface AbstractSIPBody {
    records: Array<dnsTypeSRV>;
}

export interface AbstractSMimeCertBody {
    username?: string;
    smimea: dnsTypeSMIMEA;
}

export interface AbstractScalewayChallengeBody {
    txt: dnsTypeTXT;
}

export interface AbstractServerBody {
    A?: dnsTypeA;
    AAAA?: dnsTypeAAAA;
    SSHFP?: Array<dnsTypeSSHFP>;
}

export interface AbstractXMPPBody {
    records: Array<dnsTypeSRV>;
}

export interface GoogleGSuiteBody {
    mx?: Array<dnsTypeMX>;
    validationMX?: dnsTypeMX;
}

export interface SvcsAliasBody {
    record: dnsRR;
}

export interface SvcsBIMIBody {
    txt: dnsTypeTXT;
}

export interface SvcsCAAPolicyBody {
    caa: Array<dnsTypeCAA>;
}

export interface SvcsDKIMRecordBody {
    txt: dnsTypeTXT;
}

export interface SvcsDKIMRedirectionBody {
    cname: dnsTypeCNAME;
}

export interface SvcsDMARCBody {
    txt: dnsTypeTXT;
}

export interface SvcsDMARCReportBody {
    txt: Array<dnsTypeTXT>;
}

export interface SvcsForSaleBody {
    txt: Array<dnsTypeTXT>;
}

export interface SvcsMTASTSBody {
    txt: dnsTypeTXT;
}

export interface SvcsMXsBody {
    mx: Array<dnsTypeMX>;
}

export interface SvcsNAPTRBody {
    naptr: dnsTypeNAPTR;
}

export interface SvcsOrphanBody {
    record: dnsRR;
}

export interface SvcsPTRBody {
    Record: dnsTypePTR;
}

export interface SvcsSPFBody {
    txt: dnsTypeTXT;
}

export interface SvcsSSHFPsBody {
    SSHFP?: Array<{
        algorithm: number;
        type: number;
        fingerprint: string;
    }>;
}

export interface SvcsSpecialCNAMEBody {
    cname: dnsTypeCNAME;
}

export interface SvcsTLSAsBody {
    tlsa: Array<dnsTypeTLSA>;
}

export interface SvcsTLSRPTBody {
    txt: dnsTypeTXT;
}

export interface SvcsTXTBody {
    txt: dnsTypeTXT;
}

export interface SvcsUnknownSRVBody {
    srv: Array<dnsTypeSRV>;
}

export interface ServiceBodies {
    "abstract.ACMEChallenge": AbstractACMEChallengeBody;
    "abstract.CalDAV": AbstractCalDAVBody;
    "abstract.CardDAV": AbstractCardDAVBody;
    "abstract.Delegation": AbstractDelegationBody;
    "abstract.EmailAutoConfig": AbstractEmailAutoConfigBody;
    "abstract.GithubOrgVerif": AbstractGithubOrgVerifBody;
    "abstract.GitlabPageVerif": AbstractGitlabPageVerifBody;
    "abstract.GoogleVerif": AbstractGoogleVerifBody;
    "abstract.Kerberos": AbstractKerberosBody;
    "abstract.KeybaseVerif": AbstractKeybaseVerifBody;
    "abstract.LDAP": AbstractLDAPBody;
    "abstract.LibravatarServer": AbstractLibravatarServerBody;
    "abstract.MTASTS": AbstractMTASTSBody;
    "abstract.MatrixIM": AbstractMatrixIMBody;
    "abstract.NSOnlyOrigin": AbstractNSOnlyOriginBody;
    "abstract.OpenPGP": AbstractOpenPGPBody;
    "abstract.Origin": AbstractOriginBody;
    "abstract.RFC6186": AbstractRFC6186Body;
    "abstract.SIP": AbstractSIPBody;
    "abstract.SMimeCert": AbstractSMimeCertBody;
    "abstract.ScalewayChallenge": AbstractScalewayChallengeBody;
    "abstract.Server": AbstractServerBody;
    "abstract.XMPP": AbstractXMPPBody;
    "google.GSuite": GoogleGSuiteBody;
    "svcs.Alias": SvcsAliasBody;
    "svcs.BIMI": SvcsBIMIBody;
    "svcs.CAAPolicy": SvcsCAAPolicyBody;
    "svcs.DKIMRecord": SvcsDKIMRecordBody;
    "svcs.DKIMRedirection": SvcsDKIMRedirectionBody;
    "svcs.DMARC": SvcsDMARCBody;
    "svcs.DMARCReport": SvcsDMARCReportBody;
    "svcs.ForSale": SvcsForSaleBody;
    "svcs.MTA_STS": SvcsMTASTSBody;
    "svcs.MXs": SvcsMXsBody;
    "svcs.NAPTR": SvcsNAPTRBody;
    "svcs.Orphan": SvcsOrphanBody;
    "svcs.PTR": SvcsPTRBody;
    "svcs.SPF": SvcsSPFBody;
    "svcs.SSHFPs": SvcsSSHFPsBody;
    "svcs.SpecialCNAME": SvcsSpecialCNAMEBody;
    "svcs.TLSAs": SvcsTLSAsBody;
    "svcs.TLS_RPT": SvcsTLSRPTBody;
    "svcs.TXT": SvcsTXTBody;
    "svcs.UnknownSRV": SvcsUnknownSRVBody;
}

// The body of any service, for the places holding one before knowing
// which service it belongs to.
export type ServiceBody = ServiceBodies[keyof ServiceBodies];
