// This file is part of the happyDomain (R) project.
// Copyright (c) 2020-2025 happyDomain
// Authors: Pierre-Olivier Mercier, et al.
//
// This program is offered under a commercial and under the AGPL license.
// For commercial licensing, contact us at <contact@happydomain.org>.
//
// For AGPL licensing:
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

//go:build ignore
// +build ignore

package main

import (
	"fmt"
	"io"
	"os"
	"sort"
	"time"

	"github.com/miekg/dns"
)

// getSortedTypes returns DNS types sorted by their numeric value for reproducible output
func getSortedTypes() []uint16 {
	types := make([]uint16, 0, len(dns.TypeToString))
	for ty := range dns.TypeToString {
		types = append(types, ty)
	}
	sort.Slice(types, func(i, j int) bool {
		return types[i] < types[j]
	})
	return types
}

func nsrrtype(fd io.Writer) {
	fmt.Fprint(fd, "    switch (input) {\n")
	for _, ty := range getSortedTypes() {
		rr := dns.TypeToString[ty]
		fmt.Fprintf(fd, `        case "%d":
        case %d:
            return %q;
`, ty, ty, rr)
	}
	fmt.Fprint(fd, "        default:\n            return \"#\";\n    }\n")
}

func main() {
	output := os.Args[1]

	fd, err := os.Create(output)
	if err != nil {
		panic(err)
	}
	defer fd.Close()

	// For reproducible builds, use SOURCE_DATE_EPOCH if set
	timestamp := time.Now()
	if epoch := os.Getenv("SOURCE_DATE_EPOCH"); epoch != "" {
		// SOURCE_DATE_EPOCH is used for reproducible builds
		timestamp = time.Unix(0, 0)
	}
	fmt.Fprint(fd, "// This file is generated by go generate\n// Last generation: "+timestamp.Format(time.UnixDate)+"\n\n")

	// nsrrtype
	fmt.Fprint(fd, "export function nsrrtype(input: number | string): string {\n")
	nsrrtype(fd)
	fmt.Fprint(fd, "};\n\n")
}
